### ISSUE TITLE
Compatibility with libgfortran.so.5

### ISSUE THREAD

**Issue by bgavran** [albertoruiz/hTensor#10]
I've been using hTensor for some time and after a system-wide update it broke.
After doing pretty much anything, like:
`ds # cs = listArray ds cs :: Array Double`

(which is the first command from the official tutorial), I get this error:

`can't load .so/.DLL for: /home/bgavran3/.cabal/lib/x86_64-linux-ghc-8.2.2/libHShmatrix-0.18.2.0-9dpgEdfMx3yLX7gMQcXa79-ghc8.2.2.so (libgfortran.so.4: cannot open shared object file: No such file or directory)`

I'm not sure if this is a still active project and if there's any way to make it compatible with libgfortran.so.5, which is, as far as I understand, the new version?

**Comment by albertoruiz** [comment]
The project is not actively developed but is maintained. It depends on hmatrix: if it works hTensor should also work. I think that libgfortran is an internal dependence of blas/lapack, I don't know what can be the problem.

**Comment by bgavran** [comment]
Thanks for the reply!
Turns out hmatrix was broken as well; I'm on arch linux and the recent upgrade to gcc8 required me to simply rebuild some packages, which solved the problem.
For those who have the same issue, [this thread ](https://bbs.archlinux.org/viewtopic.php?id=236900) has more info.
