### ISSUE TITLE
Array.tridx is slow

### ISSUE THREAD

**Issue by kjslag** [albertoruiz/hTensor#4]
`matrixatorFree`, `matrixator`, and `reorder` can be slow because `Array.tridx` is slow. The slowness is most pronounced for tensors with many indices (e.g. 6 indices or more). I would like to improve the performance by implementing and making use of a tensor transpose function in c, which I think should actually be added to the hmatrix package since it's a useful building block for any tensor library. Below are my plans. Please let me know if you think I should make any changes.

Add to LinearAlgebra.Element class:
```haskell
reorderV :: Vector CInt -> Vector CInt -> Vector a -> Vector a
```

Export a renamed version from LinearAlgebra.Devel:
```haskell
-- | Transpose an array with dimensions @dims@ by making a copy using @strides@. For example,
--   @(reorderVector strides dims v) ! ((i * dims ! 1 + j) * dims ! 2 + k) == v ! (i * strides ! 0 + j * strides ! 1 + k * strides ! 2)@
--   Note: the stride lengths are not checked! For example, it's assumed that the above equation does not go out of bounds if @0 <= i < dims ! 0@, @0 <= j < dims ! 1@, and @0 <= k < dims ! 2@.
reorderVector :: Vector CInt -- ^ @strides@: array strides
              -> Vector CInt -- ^ @dims@: array dimensions of original array @v@
              -> Vector a    -- ^ @v@: flattened input array
              -> Vector a    -- ^ @v'@: flattened output array
reorderVector = reorderV
```

This will require foreign imports. For example:
```haskell
foreign import ccall unsafe "reorderVF" c_reorderVF :: CV CInt (CV CInt (CV Float  (CV Float (IO CInt))))
```

**Comment by albertoruiz** [comment]
Yes, this is an excellent idea. Please do it!
